# Generated by Django 3.2.20 on 2023-08-01 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='county',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
