# Generated by Django 3.2.20 on 2023-08-31 00:52

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarMake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('car_make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.carmake')),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('price', models.IntegerField()),
                ('year', models.CharField(choices=[('2023', '2023'), ('2022', '2022'), ('2021', '2021'), ('2020', '2020'), ('2019', '2019'), ('2018', '2018'), ('2017', '2017'), ('2016', '2016'), ('2015', '2015'), ('2014', '2014'), ('2013', '2013'), ('2012', '2012'), ('2011', '2011'), ('2010', '2010'), ('2009', '2009'), ('2008', '2008'), ('2007', '2007'), ('2006', '2006'), ('2005', '2005'), ('2004', '2004'), ('2003', '2003'), ('2002', '2002'), ('2001', '2001'), ('2000', '2000'), ('1999', '1999'), ('1998', '1998'), ('1997', '1997'), ('1996', '1996'), ('1995', '1995'), ('1994', '1994'), ('1993', '1993'), ('1992', '1992'), ('1991', '1991'), ('1990', '1990')], max_length=10, null=True)),
                ('mileage', models.IntegerField(null=True)),
                ('town', models.CharField(max_length=100)),
                ('county', models.CharField(choices=[('antrim', 'Antrim'), ('armagh', 'Armagh'), ('carlow', 'Carlow'), ('cavan', 'Cavan'), ('clare', 'Clare'), ('cork', 'Cork'), ('derry', 'Derry'), ('donegal', 'Donegal'), ('down', 'Down'), ('dublin', 'Dublin'), ('fermanagh', 'Fermanagh'), ('galway', 'Galway'), ('kerry', 'Kerry'), ('kildare', 'Kildare'), ('kilkenny', 'Kilkenny'), ('laois', 'Laois'), ('leitrim', 'Leitrim'), ('limerick', 'Limerick'), ('longford', 'Longford'), ('louth', 'Louth'), ('mayo', 'Mayo'), ('meath', 'Meath'), ('monaghan', 'Monaghan'), ('offaly', 'Offaly'), ('roscommon', 'Roscommon'), ('sligo', 'Sligo'), ('tipperary', 'Tipperary'), ('tyrone', 'Tyrone'), ('waterford', 'Waterford'), ('westmeath', 'Westmeath'), ('wexford', 'Wexford'), ('wicklow', 'Wicklow')], max_length=100)),
                ('body_type', models.CharField(blank=True, choices=[('convertable', 'Convertable'), ('coupe', 'Coupe'), ('saloon', 'Saloon'), ('hatchback', 'Hatchback'), ('estate', 'Estate'), ('mpv', 'MPV'), ('suv', 'SUV'), ('van', 'Van')], max_length=100, null=True)),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('hybrid', 'Hybrid'), ('electric', 'Electric')], max_length=100)),
                ('engine_size', models.CharField(choices=[('0.8', '0.8 L'), ('1.0', '1.0 L'), ('1.2', '1.2 L'), ('1.4', '1.4 L'), ('1.6', '1.6 L'), ('1.8', '1.8 L'), ('2.0', '2.0 L'), ('2.2', '2.2 L'), ('2.4', '2.4 L'), ('2.5', '2.5 L'), ('3.0', '3.0 L'), ('3.5', '3.5 L'), ('4.0', '4.0 L'), ('4.2', '4.2 L'), ('4.6', '4.6 L'), ('5.0', '5.0 L'), ('5.5', '5.5 L'), ('6.0', '6.0 L'), ('6.2', '6.2 L'), ('7.0', '7.0 L')], max_length=20)),
                ('transmission', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic')], max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('listing_image_1', django_resized.forms.ResizedImageField(blank=True, crop=None, default='listings/default-listing-img.jpg', force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[1920, 1080], upload_to='listings/')),
                ('listing_image_2', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[1920, 1080], upload_to='listings/')),
                ('listing_image_3', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[1920, 1080], upload_to='listings/')),
                ('listing_image_4', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[1920, 1080], upload_to='listings/')),
                ('listing_image_5', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[1920, 1080], upload_to='listings/')),
                ('listing_image_6', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[1920, 1080], upload_to='listings/')),
                ('listing_image_7', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[1920, 1080], upload_to='listings/')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('car_make', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.carmake')),
                ('car_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.carmodel')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.listing')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
