# Generated by Django 3.2.20 on 2023-08-17 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='listing_image_1',
            field=models.ImageField(blank=True, default='listings/default-listing-img.jpg', null=True, upload_to='listings/'),
        ),
    ]
