# Generated by Django 3.2.20 on 2023-08-19 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_listing_listing_image_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='listing_image_7',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
