# Generated by Django 3.2.20 on 2023-08-20 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_auto_20230819_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='battery_capacity',
        ),
    ]
