# Generated by Django 3.2.20 on 2023-08-25 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_remove_listing_battery_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='car_make',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.carmake'),
        ),
    ]
