# Generated by Django 3.2.20 on 2023-08-27 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_username'),
        ('listings', '0008_listing_favourites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='favourites',
            field=models.ManyToManyField(blank=True, null=True, related_name='favourites', to='users.Profile'),
        ),
    ]
