# Generated by Django 3.2.20 on 2023-08-28 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_username'),
        ('listings', '0011_auto_20230828_1210'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favourites',
            new_name='Favourite',
        ),
    ]
