# Generated by Django 3.2.20 on 2023-08-28 22:29

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_rename_favourites_favourite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='listing_image_1',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='listings/default-listing-img.jpg', force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[1920, 1080], upload_to='listings/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listing_image_2',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[1920, 1080], upload_to='listings/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listing_image_3',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[1920, 1080], upload_to='listings/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listing_image_4',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[1920, 1080], upload_to='listings/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listing_image_5',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[1920, 1080], upload_to='listings/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listing_image_6',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[1920, 1080], upload_to='listings/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listing_image_7',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[1920, 1080], upload_to='listings/'),
        ),
    ]
